// Auto-generated version information
// Generated at: 2026-10-07T09:26:36.894157+00:00
// DO NOT EDIT MANUALLY - This file is generated by src/utils/generate_version.py

const VERSION_INFO = {
    commitCount: 376,
    shortHash: "0bb5fb7",
    fullHash: "0bb5fb7890ee08b6bd277e4766244f1610d127a1",
    commitDate: "2026-10-07T11:25:53+02:00",
    generatedAt: "2026-10-07T09:26:36.894157+00:00",

    // Formatted version string for display
    getVersionString: function() {
        return `Version ${this.commitCount} · ${this.shortHash}`;
    },

    // Full version info string
    getFullVersionString: function() {
        return `v${this.commitCount} (${this.shortHash})`;
    }
};

// Export for use in HTML pages
if (typeof window !== 'undefined') {
    window.VERSION_INFO = VERSION_INFO;
}
