// Auto-generated version information
// Generated at: 2026-08-22T14:22:13.099004+00:00
// DO NOT EDIT MANUALLY - This file is generated by src/utils/generate_version.py

const VERSION_INFO = {
    commitCount: 374,
    shortHash: "33ac89b",
    fullHash: "33ac89b7c99eec85824fd0f6c522e402d6ea698c",
    commitDate: "2026-08-22T16:20:31+02:00",
    generatedAt: "2026-08-22T14:22:13.099004+00:00",

    // Formatted version string for display
    getVersionString: function() {
        return `Version ${this.commitCount} · ${this.shortHash}`;
    },

    // Full version info string
    getFullVersionString: function() {
        return `v${this.commitCount} (${this.shortHash})`;
    }
};

// Export for use in HTML pages
if (typeof window !== 'undefined') {
    window.VERSION_INFO = VERSION_INFO;
}
