#!/usr/bin/env python3
"""
Generate version information from Git and write to a JavaScript file.

This script extracts version information from the Git repository:
- Commit count (total number of commits)
- Short commit hash (first 7 characters)
- Full commit hash
- Commit date

The version info is written to docs/version.js as a JavaScript module
that can be imported by all HTML pages to display the version.

Usage:
    python src/generate_version.py

Output:
    Creates/updates docs/version.js with version information
"""

import subprocess
import os
from datetime import datetime, timezone


def get_git_info():
    """
    Extract version information from Git repository.
    
    Returns:
        dict: Version information containing:
            - commit_count: Total number of commits
            - short_hash: Short commit hash (7 chars)
            - full_hash: Full commit hash
            - commit_date: ISO formatted commit date
            - generated_at: ISO formatted generation timestamp
    """
    try:
        # Get total commit count
        commit_count = subprocess.check_output(
            ["git", "rev-list", "--count", "HEAD"],
            text=True,
            timeout=10
        ).strip()
        
        # Get short commit hash
        short_hash = subprocess.check_output(
            ["git", "rev-parse", "--short=7", "HEAD"],
            text=True,
            timeout=10
        ).strip()
        
        # Get full commit hash
        full_hash = subprocess.check_output(
            ["git", "rev-parse", "HEAD"],
            text=True,
            timeout=10
        ).strip()
        
        # Get commit date
        commit_date = subprocess.check_output(
            ["git", "log", "-1", "--format=%cI"],
            text=True,
            timeout=10
        ).strip()
        
        return {
            "commit_count": int(commit_count),
            "short_hash": short_hash,
            "full_hash": full_hash,
            "commit_date": commit_date,
            "generated_at": datetime.now(timezone.utc).isoformat()
        }
    except subprocess.CalledProcessError as e:
        print(f"Error getting git info: {e}")
        # Fallback values if git commands fail
        return {
            "commit_count": 0,
            "short_hash": "unknown",
            "full_hash": "unknown",
            "commit_date": datetime.now(timezone.utc).isoformat(),
            "generated_at": datetime.now(timezone.utc).isoformat()
        }


def write_version_js(version_info, output_path):
    """
    Write version information to a JavaScript file.
    
    Args:
        version_info (dict): Version information from get_git_info()
        output_path (str): Path to write the JavaScript file
    """
    js_content = f"""// Auto-generated version information
// Generated at: {version_info['generated_at']}
// DO NOT EDIT MANUALLY - This file is generated by src/generate_version.py

const VERSION_INFO = {{
    commitCount: {version_info['commit_count']},
    shortHash: "{version_info['short_hash']}",
    fullHash: "{version_info['full_hash']}",
    commitDate: "{version_info['commit_date']}",
    generatedAt: "{version_info['generated_at']}",
    
    // Formatted version string for display
    getVersionString: function() {{
        return `Version ${{this.commitCount}} · ${{this.shortHash}}`;
    }},
    
    // Full version info string
    getFullVersionString: function() {{
        return `v${{this.commitCount}} (${{this.shortHash}})`;
    }}
}};

// Export for use in HTML pages
if (typeof window !== 'undefined') {{
    window.VERSION_INFO = VERSION_INFO;
}}
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✓ Version file written to {output_path}")
    print(f"  Commit count: {version_info['commit_count']}")
    print(f"  Short hash: {version_info['short_hash']}")
    print(f"  Version string: Version {version_info['commit_count']} · {version_info['short_hash']}")


def main():
    """Main entry point."""
    # Determine output path (relative to script location)
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    output_path = os.path.join(repo_root, "docs", "version.js")
    
    print("Generating version information...")
    version_info = get_git_info()
    write_version_js(version_info, output_path)
    print("✓ Version generation complete")


if __name__ == "__main__":
    main()
